public class Class01 {
    public static void main(String[] args) {

        //V1 calismalarim...
        //V2 uzerine calismalar...
        System.out.println("V3 kodlari...");//V3
        //V4 kodlari...
        //V5 calismalar...
        //GitHub degisiklikleri...
    }
}
